// <auto-generated />
using System;
using JiggysCarRental.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JiggysCarRental.Migrations
{
    [DbContext(typeof(CarDbContext))]
    [Migration("20230729224230_CarRental")]
    partial class CarRental
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JiggysCarRental.Models.Rental", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<bool>("GPSNavigation")
                        .HasColumnType("bit");

                    b.Property<bool>("InfantAndChildSeats")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RentCost")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TransactionId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("JiggysCarRental.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutomaticTransmission")
                        .HasColumnType("bit");

                    b.Property<bool>("Aux")
                        .HasColumnType("bit");

                    b.Property<bool>("Bluetooth")
                        .HasColumnType("bit");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDateAvailable")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FourWheelDrive")
                        .HasColumnType("bit");

                    b.Property<bool>("HeatedSeat")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LeatherSeats")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOLargeBags")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPassengers")
                        .HasColumnType("int");

                    b.Property<bool>("PushStart")
                        .HasColumnType("bit");

                    b.Property<string>("RentCost")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ReverseCamera")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDateAvailable")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SteeringControl")
                        .HasColumnType("bit");

                    b.Property<bool>("ThermalControl")
                        .HasColumnType("bit");

                    b.Property<bool>("ToolsControl")
                        .HasColumnType("bit");

                    b.Property<bool>("UsbAdapter")
                        .HasColumnType("bit");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
